using gbfr.transmarvel.overhaul.Configuration;

namespace gbfr.transmarvel.overhaul;

// GENERATED from game data (scripts/gen-transmarvel-code.mjs) - do not hand-edit.
public static class TraitCatalog
{
    public record Trait(uint Hash, string Name, Func<Config, bool> Enabled);

    public static readonly Trait[] All =
    {
        new(0x50079A1C, "ATK", c => c.Atk),
        new(0xF372F096, "HP", c => c.Hp),
        new(0x8D78A19B, "Critical Hit Rate", c => c.CriticalHitRate),
        new(0xCEB700EE, "Stun Power", c => c.StunPower),
        new(0x3F488339, "Enmity", c => c.Enmity),
        new(0x2FC8FBFF, "Stamina", c => c.Stamina),
        new(0xC0979A17, "Critical Hit DMG", c => c.CriticalHitDmg),
        new(0x6B694D6D, "Weak Point DMG", c => c.WeakPointDmg),
        new(0x71F11A9B, "Tyranny", c => c.Tyranny),
        new(0x8F502F0D, "Life on the Line", c => c.LifeOnTheLine),
        new(0xDC584F60, "DMG Cap", c => c.DmgCap),
        new(0xEAE321EB, "Skilled Assault", c => c.SkilledAssault),
        new(0x3FEC5F80, "Linked Together", c => c.LinkedTogether),
        new(0xF17850B9, "Combo Booster", c => c.ComboBooster),
        new(0x57AB5B10, "Supplementary DMG", c => c.SupplementaryDmg),
        new(0xA7A45F28, "Combo Finisher DMG", c => c.ComboFinisherDmg),
        new(0x1C360C63, "Charged Attack DMG", c => c.ChargedAttackDmg),
        new(0xC35B111B, "Lucky Charge", c => c.LuckyCharge),
        new(0x84078CB0, "Quick Charge", c => c.QuickCharge),
        new(0xB360801D, "Concentrated Fire", c => c.ConcentratedFire),
        new(0x8D078597, "Throw DMG", c => c.ThrowDmg),
        new(0x4F1A3683, "Injury to Insult", c => c.InjuryToInsult),
        new(0xA9D17F55, "Overdrive Assassin", c => c.OverdriveAssassin),
        new(0xAC9674C1, "Break Assassin", c => c.BreakAssassin),
        new(0x1568E0E4, "Head Start", c => c.HeadStart),
        new(0xDC225C96, "Power Hungry", c => c.PowerHungry),
        new(0x3C2B57B0, "Guard Payback", c => c.GuardPayback),
        new(0x7C2E4D64, "Dodge Payback", c => c.DodgePayback),
        new(0x82CE278D, "Less Is More", c => c.LessIsMore),
        new(0x70395731, "Berserker", c => c.Berserker),
        new(0xA8A3163B, "Glass Cannon", c => c.GlassCannon),
        new(0xE0ABFDFE, "Aegis", c => c.Aegis),
        new(0x48A95B8D, "Greater Aegis", c => c.GreaterAegis),
        new(0xE6CDBA9C, "Garrison", c => c.Garrison),
        new(0x74AA75D6, "Stronghold", c => c.Stronghold),
        new(0x1470F860, "Steel Nerves", c => c.SteelNerves),
        new(0x0AA20846, "Improved Guard", c => c.ImprovedGuard),
        new(0x8B3BF60C, "Improved Dodge", c => c.ImprovedDodge),
        new(0x29B292A8, "Precise Resilience", c => c.PreciseResilience),
        new(0x09AA7DB5, "Nimble Defense", c => c.NimbleDefense),
        new(0xB6E31F76, "Firm Stance", c => c.FirmStance),
        new(0x3759A5B9, "Dizzy Resistance", c => c.DizzyResistance),
        new(0xFB572681, "Glaciate Resistance", c => c.GlaciateResistance),
        new(0x1DC9D7E7, "Held Under Resistance", c => c.HeldUnderResistance),
        new(0xD54F8CA7, "Sandtomb Resistance", c => c.SandtombResistance),
        new(0x973B49AF, "Poison Resistance", c => c.PoisonResistance),
        new(0xA2FA9685, "Slow Resistance", c => c.SlowResistance),
        new(0x7C84A6B3, "Burn Resistance", c => c.BurnResistance),
        new(0x2242921F, "Paralysis Resistance", c => c.ParalysisResistance),
        new(0x9702860F, "Blight Resistance", c => c.BlightResistance),
        new(0x50B453DD, "Skill Sealed Resistance", c => c.SkillSealedResistance),
        new(0xCFB48782, "SBA Sealed Resistance", c => c.SbaSealedResistance),
        new(0xDD4A701E, "Darkflame Resistance", c => c.DarkflameResistance),
        new(0x4BF2E191, "ATK↓ Resistance", c => c.AtkDownResistance),
        new(0x66DE60B1, "DEF↓ Resistance", c => c.DefDownResistance),
        new(0x9389CC06, "Improved Healing", c => c.ImprovedHealing),
        new(0x6085DA25, "Regen", c => c.Regen),
        new(0x7CCFF74F, "Drain", c => c.Drain),
        new(0x318D12E9, "Quick Cooldown", c => c.QuickCooldown),
        new(0x05F2ECDC, "Cascade", c => c.Cascade),
        new(0xB5FF9FD3, "Uplift", c => c.Uplift),
        new(0x7EDD69D0, "Precise Wrath", c => c.PreciseWrath),
        new(0xD2C8E10A, "Nimble Onslaught", c => c.NimbleOnslaught),
        new(0x24883AF3, "Potion Hoarder", c => c.PotionHoarder),
        new(0xE69A4694, "Guts", c => c.Guts),
        new(0x95F3FA86, "Autorevive", c => c.Autorevive),
        new(0x0053599E, "Steady Focus", c => c.SteadyFocus),
        new(0x6018372B, "Provoke", c => c.Provoke),
        new(0xDC607D75, "Low Profile", c => c.LowProfile),
        new(0xF687C5EF, "Fast Learner", c => c.FastLearner),
        new(0xC86F3082, "Rupie Tycoon", c => c.RupieTycoon),
        new(0x5E422AE5, "Path to Mastery", c => c.PathToMastery),
    };
}
